In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
myarr=np.array(mylist)

In [6]:
myarr

array([1, 2, 3])

In [7]:
type(myarr)

numpy.ndarray

In [8]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [25]:
np.random.rand(2,3)

array([[0.0490156 , 0.92687197, 0.65040799],
       [0.61788917, 0.22819123, 0.94134248]])

In [27]:
np.random.randn(2,3)

array([[-0.63879638, -0.92981081,  1.50655691],
       [ 0.21746302,  0.91291132, -1.91974527]])

In [31]:
np.random.randint(2,99,(4,2))

array([[19, 26],
       [22,  3],
       [29, 32],
       [83, 11]])

In [32]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [37]:
arr = np.arange(1,26)

In [43]:
arr.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [44]:
ranarr = np.random.randint(0,102,10)

In [45]:
ranarr


array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [46]:
ranarr.max()

99

In [47]:
ranarr.min()

2

In [48]:
ranarr.argmax()

5

In [49]:
ranarr.argmin()

7

In [50]:
ranarr.dtype

dtype('int32')

In [51]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [52]:
arr.shape

(25,)

In [54]:
arr = arr.reshape(5,5)

In [55]:
arr.shape

(5, 5)

In [2]:
import numpy as np

In [3]:
arr = np.arange(1,11)

In [4]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[4]

5

In [6]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [7]:
arr[2:5]


array([3, 4, 5])

In [8]:
arr_copy = arr.copy()

In [9]:
arr_copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr_copy = np.arange(0,11)

In [11]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr_copy[0:4]=23

In [13]:
arr_copy

array([23, 23, 23, 23,  4,  5,  6,  7,  8,  9, 10])

1. Slicing points to the location
2. Changes in sliced arr changes the original array

In [19]:
arr_2d = np.random.randint(0,99,(3,3))

In [20]:
arr_2d

array([[91, 83, 79],
       [ 3, 29, 64],
       [75, 11, 55]])

1. To get certain rows and columns 
2. Not used a whole lot

In [21]:
arr_2d[1:]

array([[ 3, 29, 64],
       [75, 11, 55]])

In [22]:
arr_2d[1:][0:1]

array([[ 3, 29, 64]])

In [24]:
arr_2d[:2,1:]

array([[83, 79],
       [29, 64]])

In [25]:
arr_2d[2,1]

11

In [26]:
arr_2d

array([[91, 83, 79],
       [ 3, 29, 64],
       [75, 11, 55]])

In [27]:
arr_2d > 50

array([[ True,  True,  True],
       [False, False,  True],
       [ True, False,  True]])

In [30]:
bool_arr = arr_2d>50


In [31]:
bool_arr

array([[ True,  True,  True],
       [False, False,  True],
       [ True, False,  True]])

In [47]:
arr[arr_2d[:1]>50]


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [34]:
arr=np.random.randint(0,100,10)

In [35]:
arr


array([94, 97, 93, 34, 73, 75, 68, 31, 53, 66])

In [42]:
arr[arr>50]

array([94, 97, 93, 73, 75, 68, 53, 66])

In [44]:
bool_arr=arr>50
arr[bool_arr]

array([94, 97, 93, 73, 75, 68, 53, 66])

Operations on arrays
